@startuml
class Main{}

interface Image{}
interface ImageBloater{
    +Image bloat(Image img)
    +Image debloat(Image img)
}

class PNG implements Image{}
class PNGBloater implements ImageBloater{}

class TUI{}

Main --> TUI
Main --> PNG
Main --> PNGBloater

@enduml